# config/settings.py

"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.0.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-^qxur*r_ro$ja&+z*_7i$pe69!yfqo7axmaigpv90)3c4!+c^8"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    # adicionado para o allauth (necessário para dj-rest-auth)
    "django.contrib.sites", 
    
    # apps do Projeto (Monolito Modular)
    "accesshub.apps.AccesshubConfig", # Nosso app de autenticação e perfis
    
    # bibliotecas de API (DRF, CORS)
    "rest_framework",
    "rest_framework.authtoken",
    "corsheaders", 
    
    # autenticação REST/Allauth
    "dj_rest_auth", 
    "allauth", 
    "allauth.account",
    "allauth.socialaccount",
]

# django.contrib.sites (para o allauth)
SITE_ID = 1

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    # **********************************************
    # CORS MIDDLEWARE
    "corsheaders.middleware.CorsMiddleware",
    # **********************************************
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    # **********************************************
    # ALLAUTH MIDDLEWARE
    "allauth.account.middleware.AccountMiddleware",
    # **********************************************
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"



# *******************************************************************
# CONFIGURAÇÕES DE API E AUTENTICAÇÃO
# *******************************************************************

# lista de origens permitidas (Next.js rodando localmente)
CORS_ALLOWED_ORIGINS = [
    "http://127.0.0.1:3000",
    "http://localhost:3000",
]


# CORS Headers Settings
# allows front-end to send auth cookies
CORS_ALLOW_CREDENTIALS = True 


CSRF_COOKIE_NAME = "csrftoken"
SESSION_COOKIE_NAME = "sessionid"

CSRF_TRUSTED_ORIGINS = [
    "http://127.0.0.1:3000",
    "http://localhost:3000",
]

# JS read cookie para enviar no cabeçalho X-CSRFToken
CSRF_COOKIE_HTTPONLY = False 
# cookie de sessão enviado em requisições cross-site de mesma origem (IP)
SESSION_COOKIE_HTTPONLY = True

# configurações de Cookie (permitir o Decoupled Auth em desenvolvimento)
# frontend (3000) != backend (8000)
# SESSION_COOKIE_SAMESITE = 'None'
# CSRF_COOKIE_SAMESITE = 'None'


SESSION_COOKIE_DOMAIN = "127.0.0.1"
CSRF_COOKIE_DOMAIN = "127.0.0.1"

# força uso de cookies seguros (via HTTPS), 
# ***** é necessário em dev com SAMESITE='None' *****
# SESSION_COOKIE_SECURE = True 
# CSRF_COOKIE_SECURE = True 

# ***** ALTERAÇÃO PARA TESTES HTTP LOCAL *****
SESSION_COOKIE_SECURE = False 
CSRF_COOKIE_SECURE = False


# --- CONFIGURAÇÃO ALLAUTH v65+ ---
# novo padrão é usar listas para métodos de login
ACCOUNT_LOGIN_METHODS = {'email'} 
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_USERNAME_REQUIRED = False
ACCOUNT_EMAIL_VERIFICATION = 'none' 
LOGIN_REDIRECT_URL = '/'
ACCOUNT_USER_MODEL_USERNAME_FIELD = None 

# --- CONFIGURAÇÃO DJ-REST-AUTH ---
REST_AUTH = {
    'USE_JWT': False, # usando Session/Cookies
    'SESSION_LOGIN': True,
    # serializer procura email se o automático falhar
    'LOGIN_SERIALIZER': 'dj_rest_auth.serializers.LoginSerializer',
}

# REST Framework Settings
# mecanismo de autenticação padrão para a API
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.SessionAuthentication', 
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    )
}
